version: '3.8'

services:
  organo:
    container_name: organo
    image: organo-image
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true